export const GET_AUTH_TOKEN_SUCCEEDED = 'GET_AUTH_TOKEN_SUCCEEDED';
export const GET_AUTH_TOKEN = 'GET_AUTH_TOKEN';
export const SET_AUTH_TOKEN_SUCCEEDED = 'SET_AUTH_TOKEN_SUCCEEDED';
export const FLAG_GETTING_AUTH_TOKEN = 'FLAG_GETTING_AUTH_TOKEN';
