export const GET_AUTH_TOKEN_SUCCEEDED = 'GET_AUTH_TOKEN_SUCCEEDED';
export const GET_ITEM_DATA = 'GET_ITEM_DATA';
export const GET_AUTH_TOKEN = 'GET_AUTH_TOKEN';
export const SET_AUTH_TOKEN_SUCCEEDED = 'SET_AUTH_TOKEN_SUCCEEDED';
export const SET_ITEM_DATA_SUCCEEDED = 'SET_ITEM_DATA_SUCCEEDED';
export const GET_ITEM_DATA_SUCCEEDED = 'GET_ITEM_DATA_SUCCEEDED';
export const FLAG_GETTING_ITEM_DATA = 'FLAG_GETTING_ITEM_DATA';
